### ISSUE TITLE
 CloudForms integrations with puppet

### ISSUE THREAD

**Issue by coolpalani** [ramrexx/CloudForms_Chef#1]
Hello,

Could you share the steps for CloudForms integrations with puppet.
Thanks in advance.

**Comment by ramrexx** [comment]
I do not have anything in my library but here are some resources you may find useful.

[http://cloudformsblog.redhat.com/2013/06/24/integrating-cloudforms-with-puppet-quru/](url)
[https://access.redhat.com/webassets/avalon/d/Mastering_CloudForms_Automation_Red_Hat/Mastering_CloudForms_Automation_Red_Hat.pdf](url)

I hope this helps.

**Comment by coolpalani** [comment]
Thanks for the responsed

*Best Regards,*
*Palanisamy*
