### ISSUE TITLE
Undefined Method Error in chef_bootstrap_windows.rb

### ISSUE THREAD

**Issue by AMC-7** [ramrexx/CloudForms_Chef#3]
chef_bootstrap_windows.rb, line 153.

The check of ```bootstrap_result.success?``` on line 153 throws an undefined method error ```[undefined method `success?' for false:FalseClass]``` when the call to ```call_chef``` encounters an error and/or timeout and hits the rescue statement and returns false.

**Comment by ramrexx** [comment]
I will need a little more information. If success? is undefined then your chef command did not run for some reason. I would investigate in the automation.log by looking for the line that has something like this:
      
log(:info, "Executing [#{cmd}] with timeout of #{timeout} seconds")

**Comment by AMC-7** [comment]
Hi,

> [----] E, [2018-05-01T09:35:09.658176 #19883:9fbc1c] ERROR -- : Q-task_id([miq_provision_490]) <AEMethod chef_bootstrap_windows> Error executing chef: Timeout::Error execution expired /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:271:in `value'......

I understand that the chef run didn't complete (in my case timed out), but instead of failing by falling into the else (line 158) it throws the error ```[undefined method `success?' for false:FalseClass]``` and continues to process through the workflow.

**Comment by AMC-7** [comment]
More complete trace:

```[----] E, [2018-05-01T09:35:09.658176 #19883:9fbc1c] ERROR -- : Q-task_id([miq_provision_490]) <AEMethod chef_bootstrap_windows> Error executing chef: Timeout::Error execution expired /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:271:in `value'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:271:in `block in capture3'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:95:in `popen3'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open3.rb:258:in `capture3'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/awesome_spawn-1.4.1/lib/awesome_spawn.rb:119:in `launch'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/awesome_spawn-1.4.1/lib/awesome_spawn.rb:79:in `run'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/linux_admin-1.0.1/lib/linux_admin/common.rb:19:in `run'
/MyCompany/Integration/Chef/StateMachines/chef_bootstrap_windows:38:in `block in call_chef'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/MyCompany/Integration/Chef/StateMachines/chef_bootstrap_windows:36:in `call_chef'
/MyCompany/Integration/Chef/StateMachines/chef_bootstrap_windows:152:in `<main>'
[----] E, [2018-05-01T09:35:09.659863 #19883:9fbc1c] ERROR -- : Q-task_id([miq_provision_490]) <AEMethod chef_bootstrap_windows> [undefined method `success?' for false:FalseClass]
/MyCompany/Integration/Chef/StateMachines/chef_bootstrap_windows:153:in `<main>'
```

**Comment by ramrexx** [comment]
What happens when you run the bootstrap command on the cloudforms command line? Does it timeout? How long does it take if it does work? I would investigate why it is taking so long to bootstrap from the command line first.

**Comment by AMC-7** [comment]
Currently looking into why it timed out and we updated line 153 with the following:
```
#rubocop:disable Style/SafeNavigation
if bootstrap_result && bootstrap_result.success?
```

and also line 153 in the chef_bootstrap_unknown.rb.
